
title: Pradyumn Dayal
email: you@example.com
description: >-
  Economic consultant and analyst. Formerly McKinsey. Interested in spatial markets and competition.
baseurl: ""
url: "https://pradyumndayal.com"
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
