
title: Pradyumn Dayal
email: pradyumn.dayal@gmail.com
description: >-
  Economic consultant and Senior Associate at Keystone.ai. Formerly McKinsey. Interested in mergers, competition, and antitrust.
baseurl: ""
url: "https://pradyumndayal.com"
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
