
title: Pradyumn Dayal
email: pradyumn.dayal@gmail.com
description: >-
  Economic consultant
baseurl: ""
url: "https://pradyumndayal.com"
theme: minima

sass:
  style: compressed

include:
  - assets/css

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
